### PR TITLE
Adds decoding of core transceiver monitors

### PR DESCRIPTION
**Pull request by bnaecker**
- Restructures the `decode` crate a bit, splitting out modules by what they decode.
- Adds the `monitors` module, with a `Monitors` type for pulling out the temp, voltage and per-lane Rx power and Tx bias current and power.
- Adds SFF-8636 decoding, with test.

### CODE REVIEW

**Comment by bnaecker** [comment]
Not completed, still need CMIS parsing and actual testing. Only SFF-8636 modules are parsed now. Will address #65 when completed.

**Comment by bnaecker** [comment]
CMIS decoding is mostly done and tested. Now need to test on real transceivers.

**Comment by bnaecker** [comment]
Rebased on #71

**Comment by bnaecker** [comment]
I've tested this (and found a bug!) on `paris` using the following transceivers:

```
BRM42220066-switch # ./xcvradm -i sidecar0 -t 4-6,20-22 vendor-info
Port Identifier           Vendor           Part             Rev  Serial           Mfg date
   4 Qsfp28 (0x11)        Intel Corp       SPTSLP3SLCFD     01   PJF1221200C4P    221028
   5 Qsfp28 (0x11)        Intel Corp       SPTSBP3CLCCO     01   CRCL2028000TS    22010400
   6 Qsfp28 (0x11)        Intel Corp       SPTSLP3SLCFD     01   PJF1221300N3P    221028
  20 Qsfp28 (0x11)        Intel Corp       SPTSBP3CLCCO     01   CRCL2028000CS    22010400
  21 QsfpPlusCmis (0x1e)  FINISAR CORP.    FTCC1122E1PLL    B    X4MAS8B          210118
  22 QsfpPlusCmis (0x1e)  FINISAR CORP.    FTCC1122E1PLL    B    X4QA275          210118
```

The monitoring data is exposed with:

```
BRM42220066-switch # ./xcvradm -i sidecar0 -t 4-6,20-22 monitors
Port 4
         Temperature (C): 27.289063
      Supply voltage (V): 3.4327998
       Avg Rx power (mW): [0.0076,0.0000,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0001,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --

Port 5
         Temperature (C): --
      Supply voltage (V): --
       Avg Rx power (mW): [0.0000,0.0000,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0000,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --

Port 6
         Temperature (C): 26.554688
      Supply voltage (V): 3.4849
       Avg Rx power (mW): [0.0001,0.0000,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0001,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --

Port 20
         Temperature (C): --
      Supply voltage (V): --
       Avg Rx power (mW): [0.0000,0.0003,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0000,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --

Port 21
         Temperature (C): 25.882813
      Supply voltage (V): 3.3572998
       Avg Rx power (mW): [0.0001,0.0001,0.0001,0.0001,0.0000,0.0000,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0001,0.0001,0.0001,0.0001,0.0000,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --

Port 22
         Temperature (C): 26.171875
      Supply voltage (V): 3.372
       Avg Rx power (mW): [0.0001,0.0001,0.0001,0.0001,0.0000,0.0000,0.0000,0.0000]
            Tx bias (mA): [0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000]
           Tx power (mW): [0.0001,0.0001,0.0001,0.0001,0.0000,0.0000,0.0000,0.0000]
                   Aux 1: --
                   Aux 2: --
                   Aux 3: --
```

Picking part one of these, it looks like the decoding works. For example, take port 4, which is an SFF-8636 module. That advertises support in byte 220:

```
BRM42220066-switch # ./xcvradm -i sidecar0 -t 4 read-upper --sff 220 1 --binary
Port Data
   4 [0b00111101]
```

Bits 0-1 are reserved. Bit 2 indicates Tx power measurements are supported. Bit 3 indicates receiver power measurements are supported, and report the average power. Bits 4 and 5 indicate support for supply voltage and temperature monitoring, respectively. 

The decoding of the supply voltage appears accurate. Bytes 26 and 27 are the most and least significant bits of the voltage, which has a resolution of 100uV. So reading those values directly, we see:

```
BRM42220066-switch # ./xcvradm -i sidecar0 -t 4 read-lower --sff 26 2
Port Data
   4 [0x86,0x0b]
```

Some quick Python shows that's pretty close to the last reported value:

```
bnaecker@feldspar : ~ $ python3 -c 'print(0x860b * 100e-6)'
3.4315
```

The same process can be used to show that the temperature is also accurately decoded.

The monitored power is harder to verify. I ran into https://github.com/oxidecomputer/dendrite/issues/247 while trying to bring the links up, and can't really get around it. That only means that I'm not sure I can convince the transceivers to actually send any light, meaning I'm not sure how to verify the optical power.

**Review by Aaron-Hartwig — APPROVED** [review]

**Pull request merged**
